// Fichier généré par outils/images.mjs à partir de credits.json : ne pas modifier à la main.
// Une image n'est affichée sur le site que si son statut est « validee » (vérifiée par Julien).
export const IMAGES = [
  {"id":"de-gaulle-londres","chapitre":"france-occupee","exercice":"qui","reponse":"Charles de Gaulle","distracteurs":["Philippe Pétain","Jean Moulin","Pierre Laval"],"recherche":"Charles de Gaulle 1942 portrait London","attendu":"Portrait du général de Gaulle pendant la guerre (1940-1944)","commons":"De Gaulle-OWI.jpg","fichier":"doc-e3434fc1fe.webp","licence":"Public domain","auteur":"Office of War Information, Overseas Picture Division","date":"circa 1942","url":"https://commons.wikimedia.org/wiki/File:De_Gaulle-OWI.jpg","statut":"en_attente"},
  {"id":"petain-portrait","chapitre":"france-occupee","exercice":"qui","reponse":"Philippe Pétain","distracteurs":["Charles de Gaulle","Georges Clemenceau","Jean Moulin"],"recherche":"Philippe Pétain portrait 1941","attendu":"Portrait officiel du maréchal Pétain, chef de l'État français","commons":"Pétain - Portrait photographique 1941 (3x4 cropped).jpg","fichier":"doc-ce8e7fde29.webp","licence":"Public domain","auteur":"Imprimerie Draeger (Montrouge)","date":"1941","url":"https://commons.wikimedia.org/wiki/File:P%C3%A9tain_-_Portrait_photographique_1941_(3x4_cropped).jpg","statut":"en_attente"},
  {"id":"jean-moulin","chapitre":"france-occupee","exercice":"qui","reponse":"Jean Moulin","distracteurs":["Charles de Gaulle","Pierre Laval","Philippe Leclerc de Hauteclocque"],"recherche":"Jean Moulin résistant photographie","attendu":"Photographie de Jean Moulin (écharpe et chapeau), années 1930","commons":null,"fichier":null,"licence":null,"auteur":null,"date":null,"url":null,"statut":"a_rechercher"},
  {"id":"croix-de-lorraine","chapitre":"france-occupee","exercice":"symbole","reponse":"La croix de Lorraine, symbole de la France libre","distracteurs":["La francisque, symbole du régime de Vichy","La croix gammée, symbole du nazisme","La faucille et le marteau, symbole du communisme"],"recherche":"Flag of Free France 1940-1944","attendu":"Drapeau tricolore de la France libre avec la croix de Lorraine","commons":"Flag of Free France (1940-1944).svg","fichier":"doc-9ae3e3ef49.webp","licence":"Public domain","auteur":"Contributeurs de Wikimedia Commons","date":"1940-1944","url":"https://commons.wikimedia.org/wiki/File:Flag_of_Free_France_(1940-1944).svg","statut":"en_attente"},
  {"id":"clemenceau","chapitre":"premiere-guerre","exercice":"qui","reponse":"Georges Clemenceau","distracteurs":["Philippe Pétain","Woodrow Wilson","Guillaume II"],"recherche":"Georges Clemenceau Nadar portrait","attendu":"Portrait photographique de Georges Clemenceau","commons":"Georges Clemenceau par Nadar.jpg","fichier":"doc-baf826690c.webp","licence":"Public domain","auteur":"Paul Nadar","date":"1904","url":"https://commons.wikimedia.org/wiki/File:Georges_Clemenceau_par_Nadar.jpg","statut":"en_attente"},
  {"id":"affiche-mobilisation-1914","chapitre":"premiere-guerre","exercice":"date","reponse":"1914","distracteurs":["1870","1918","1939"],"recherche":"Ordre de mobilisation générale 1914 affiche","attendu":"Affiche de l'ordre de mobilisation générale du 1er août 1914","commons":"Ordre de Mobilisation générale 2 août 1914.jpg","fichier":"doc-247e95cdde.webp","licence":"Public domain","auteur":"French Government","date":"1914-08-01","url":"https://commons.wikimedia.org/wiki/File:Ordre_de_Mobilisation_g%C3%A9n%C3%A9rale_2_ao%C3%BBt_1914.jpg","statut":"en_attente"},
  {"id":"churchill","chapitre":"seconde-guerre","exercice":"qui","reponse":"Winston Churchill","distracteurs":["Franklin D. Roosevelt","Joseph Staline","Charles de Gaulle"],"recherche":"Winston Churchill 1941 portrait","attendu":"Portrait de Winston Churchill, Premier ministre britannique","commons":"Winston Churchill cph.3a49758 (cropped).jpg","fichier":"doc-837287fd1d.webp","licence":"Public domain","auteur":"J. Russell and Sons","date":"1941","url":"https://commons.wikimedia.org/wiki/File:Winston_Churchill_cph.3a49758_(cropped).jpg","statut":"en_attente"},
  {"id":"drapeau-urss","chapitre":"guerre-froide","exercice":"symbole","reponse":"La faucille et le marteau, symbole du communisme","distracteurs":["La croix de Lorraine, symbole de la France libre","Les douze étoiles, symbole de l'Union européenne","La bannière étoilée, symbole des États-Unis"],"recherche":"Flag of the Soviet Union","attendu":"Drapeau de l'URSS (faucille et marteau)","commons":"Flag of the Soviet Union.svg","fichier":"doc-db87677a58.webp","licence":"Public domain","auteur":"URSS (domaine public)","date":"1955 (modèle officiel)","url":"https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg","statut":"en_attente"},
  {"id":"mur-berlin-1989","chapitre":"guerre-froide","exercice":"date","reponse":"1989","distracteurs":["1961","1945","1991"],"recherche":"Berlin Wall November 1989 Brandenburg Gate","attendu":"Photographie de Berlinois sur le mur devant la porte de Brandebourg, novembre 1989","commons":"West and East Germans at the Brandenburg Gate in 1989.jpg","fichier":"doc-af103c4544.webp","licence":"CC BY-SA 3.0","auteur":"Unknown photographer, Reproduction by Lear 21 at English Wikipedia","date":"1989","url":"https://commons.wikimedia.org/wiki/File:West_and_East_Germans_at_the_Brandenburg_Gate_in_1989.jpg","statut":"en_attente"},
  {"id":"drapeau-europe","chapitre":"europe","exercice":"symbole","reponse":"Les douze étoiles, symbole de l'Union européenne","distracteurs":["La faucille et le marteau, symbole du communisme","La croix de Lorraine, symbole de la France libre","La bannière étoilée, symbole des États-Unis"],"recherche":"Flag of Europe","attendu":"Drapeau européen (cercle de douze étoiles dorées sur fond bleu)","commons":"Flag of Europe.svg","fichier":"doc-395d47c2fd.webp","licence":"Public domain","auteur":"Contributeurs de Wikimedia Commons","date":null,"url":"https://commons.wikimedia.org/wiki/File:Flag_of_Europe.svg","statut":"en_attente"},
  {"id":"simone-veil","chapitre":"societe-1950-1980","exercice":"qui","reponse":"Simone Veil","distracteurs":["Gisèle Halimi","Louise Weiss","Marie Curie"],"recherche":"Simone Veil 1975 portrait","attendu":"Portrait de Simone Veil, ministre de la Santé (années 1970)","commons":"Simone Veil (1984).jpg","fichier":"doc-8d4618f9d3.webp","licence":"CC0","auteur":"Rob Croes for Anefo","date":"1984-06-23","url":"https://commons.wikimedia.org/wiki/File:Simone_Veil_(1984).jpg","statut":"en_attente"},
  {"id":"de-gaulle-president","chapitre":"cinquieme-republique","exercice":"qui","reponse":"Charles de Gaulle","distracteurs":["Georges Pompidou","François Mitterrand","Valéry Giscard d'Estaing"],"recherche":"Charles de Gaulle 1961 president portrait","attendu":"Portrait du président de Gaulle (années 1960)","commons":"Charles de Gaulle-1963.jpg","fichier":"doc-c3e5276963.webp","licence":"CC BY-SA 3.0 de","auteur":"Ludwig Wegmann","date":"1963-07-04","url":"https://commons.wikimedia.org/wiki/File:Charles_de_Gaulle-1963.jpg","statut":"en_attente"}
];

export function imageValidee(id) {
  const im = IMAGES.find(x => x.id === id);
  return !!(im && im.statut === 'validee' && im.fichier);
}

export function imagesValidees(chapitre) {
  return IMAGES.filter(x => x.statut === 'validee' && x.fichier && (!chapitre || x.chapitre === chapitre));
}

// Légende de crédit affichée sous chaque image (sans la date quand on demande de dater le document)
export function credit(im, sansDate = false) {
  return `${im.auteur || 'Auteur inconnu'}${im.date && !sansDate ? `, ${im.date}` : ''} · ${im.licence} · Wikimedia Commons`;
}
