// Situations pratiques · Être citoyen : voter, s'engager
import { fabriquerSituations, SITUATION_INVENTEE } from './fabrique-situation.js';

export default fabriquerSituations([
  {
    id: 'vote',
    titre: 'Voter, est-ce utile ?',
    documents: [
      { titre: 'Un débat entre lycéens', html: '<p>À l\'approche d\'élections, un groupe de jeunes de 18 ans discute. L\'un affirme : « Voter ne sert à rien, ma voix ne compte pas. » Une autre répond qu\'elle ira voter, car ce sont les élus qui décident des lois, des transports ou des écoles. Un troisième rappelle que des personnes se sont battues pour obtenir le droit de vote, comme les femmes en France en 1944.</p>', source: SITUATION_INVENTEE },
      { titre: 'Le suffrage dans la Constitution', html: '<p>« La souveraineté nationale appartient au peuple qui l\'exerce par ses représentants et par la voie du référendum. […] Le suffrage […] est toujours <u>universel, égal et secret</u>. Sont électeurs, dans les conditions déterminées par la loi, tous les nationaux français majeurs des deux sexes, jouissant de leurs droits civils et politiques. »</p>', source: 'Constitution de la Ve République, article 3 (extraits).' }
    ],
    definition: { consigne: 'Qu\'est-ce que le suffrage universel ?', mots: [['vote', 'voter'], ['tous', 'tout'], ['citoyens', 'majeurs']], corrige: 'Le suffrage universel est le droit de vote accordé à tous les citoyens majeurs, sans distinction de sexe, de richesse ou d\'origine.' },
    analyse: { consigne: 'Pourquoi peut-on dire que l\'abstention affaiblit la démocratie ?', mots: [['élus', 'représentants'], ['peuple', 'citoyens'], ['moins', 'décid']], corrige: 'Quand beaucoup de citoyens ne votent pas, les élus sont choisis par une petite partie du peuple. Les décisions représentent alors moins bien l\'ensemble des citoyens.' },
    principe: { consigne: 'Identifie et définis le principe de la République affirmé par l\'article 3.', mots: [['souveraineté'], ['peuple'], ['démocratie', 'démocratique']], corrige: 'C\'est la souveraineté nationale, principe d\'une République démocratique : le pouvoir appartient au peuple, qui l\'exerce par ses représentants élus et par le référendum.' },
    explication: { consigne: 'Explique pourquoi voter est à la fois un droit et un devoir civique. Illustre par deux exemples tirés des documents.', mots: [['droit'], ['devoir'], ['1944', 'femmes'], ['élus', 'lois']], corrige: 'Voter est un droit garanti par la Constitution à tous les Français majeurs. Ce droit a été obtenu par des luttes, par exemple pour les femmes en 1944. C\'est aussi un devoir civique, même s\'il n\'est pas obligatoire en France. En votant, le citoyen choisit les élus qui font les lois et décident des transports ou des écoles. Celui qui ne vote pas laisse les autres décider à sa place.' },
    texte: { consigne: 'Écris un texte pour convaincre les jeunes qui auront bientôt 18 ans d\'aller voter.', lignes: 8, mots: [['voter', 'vote'], ['droit'], ['élus', 'décid'], ['citoyen']], corrige: 'Bientôt, tu auras 18 ans et tu pourras voter : ne laisse pas passer cette chance. D\'abord, voter est un droit précieux que d\'autres ont obtenu par leurs combats, comme les femmes en 1944. Ensuite, les élus que tu choisis décident de choses très concrètes : les lois, les écoles, les transports, l\'environnement. Si tu ne votes pas, d\'autres choisiront à ta place. Le vote est secret, donc personne ne peut te forcer à voter pour quelqu\'un. Enfin, voter, c\'est montrer que tu es un citoyen qui participe à la vie démocratique. Alors, inscris-toi et vote.' }
  },
  {
    id: 'engagement',
    titre: 'S\'engager pour les autres',
    documents: [
      { titre: 'Un projet d\'élèves', html: '<p>Dans un collège, des éco-délégués constatent que la cantine jette beaucoup de pain. Avec l\'aide du gestionnaire, ils installent une table de tri, pèsent les déchets chaque semaine et affichent les résultats. En trois mois, le gaspillage diminue nettement. Certains élèves décident ensuite de rejoindre une association qui récupère les invendus pour une épicerie solidaire.</p>', source: SITUATION_INVENTEE },
      { titre: 'La liberté d\'association', html: '<p>« L\'association est la convention par laquelle deux ou plusieurs personnes <u>mettent en commun</u>, d\'une façon permanente, leurs connaissances ou leur activité <u>dans un but autre que de partager des bénéfices</u>. »</p>', source: 'Loi du 1er juillet 1901 relative au contrat d\'association, article 1er.' }
    ],
    definition: { consigne: 'Qu\'est-ce qu\'une association ?', mots: [['personnes', 'membres'], ['commun', 'ensemble'], ['bénéfices', 'profit', 'but']], corrige: 'Une association est un groupe de personnes qui mettent en commun leur activité dans un but autre que de partager des bénéfices.' },
    analyse: { consigne: 'En quoi l\'action des éco-délégués est-elle un engagement ?', mots: [['agir', 'agiss', 'action'], ['tous', 'collège', 'collectif', 'autres'], ['gaspillage', 'environnement']], corrige: 'Les éco-délégués agissent volontairement pour l\'intérêt de tous les élèves et pour l\'environnement. Ils réduisent le gaspillage de la cantine.' },
    principe: { consigne: 'Identifie et définis la valeur de la République illustrée par l\'épicerie solidaire.', mots: [['fraternité', 'solidarité'], ['aide', 'aider', 'entraide'], ['autres']], corrige: 'C\'est la fraternité : les citoyens sont solidaires et s\'entraident, en particulier avec les personnes en difficulté.' },
    explication: { consigne: 'Montre qu\'on peut s\'engager avant d\'avoir 18 ans. Illustre par deux exemples tirés des documents.', mots: [['délégué', 'éco-délégué'], ['association'], ['collège'], ['engag']], corrige: 'Même sans avoir le droit de vote, un collégien peut s\'engager. Au collège, il peut être délégué de classe ou éco-délégué, comme les élèves du document 1. Ils ont réduit le gaspillage de pain à la cantine. Un jeune peut aussi rejoindre une association, grâce à la liberté d\'association garantie par la loi de 1901. Par exemple, certains élèves aident une épicerie solidaire.' },
    texte: { consigne: 'Écris un texte pour encourager tes camarades à s\'engager au collège ou dans une association.', lignes: 8, mots: [['engag'], ['association', 'délégué'], ['solidar', 'fraternité', 'aider'], ['citoyen']], corrige: 'Tu penses peut-être qu\'il faut être adulte pour changer les choses, mais ce n\'est pas vrai. D\'abord, au collège, tu peux devenir délégué ou éco-délégué : tu représentes tes camarades et tu proposes des projets, comme la lutte contre le gaspillage à la cantine. Ensuite, tu peux rejoindre une association sportive, culturelle ou solidaire, car beaucoup acceptent les jeunes. S\'engager permet d\'aider les autres et de vivre la fraternité. Enfin, tu apprends à travailler en équipe et à défendre tes idées. C\'est ainsi qu\'on devient un citoyen actif.' }
  }
]);
