// Situations pratiques · S'informer : désinformation et esprit critique
import { fabriquerSituations, SITUATION_INVENTEE } from './fabrique-situation.js';

export default fabriquerSituations([
  {
    id: 'rumeur',
    titre: 'Une fausse information au collège',
    documents: [
      { titre: 'Un message qui circule', html: '<p>Un lundi matin, une capture d\'écran circule sur les téléphones des élèves d\'un collège. Elle affirme, avec le logo du collège, que « les cours sont annulés toute la semaine à cause d\'un virus ». En une heure, le message est partagé plus de 300 fois. Le principal publie un démenti : le message est faux et le logo a été copié. Plusieurs élèves sont pourtant restés chez eux.</p>', source: SITUATION_INVENTEE },
      { titre: 'La liberté d\'expression', html: '<p>« La libre communication des pensées et des opinions est un des droits les plus précieux de l\'Homme : tout Citoyen peut donc parler, écrire, imprimer librement, <u>sauf à répondre de l\'abus de cette liberté</u> dans les cas déterminés par la Loi. »</p>', source: 'Déclaration des droits de l\'homme et du citoyen, article 11, 26 août 1789.' }
    ],
    definition: { consigne: 'Qu\'est-ce qu\'une fausse information (ou « infox ») ?', mots: [['fausse', 'faux'], ['volontaire', 'tromper', 'manipuler'], ['présentée', 'vraie']], corrige: 'Une fausse information est une information inexacte présentée comme vraie, souvent diffusée volontairement pour tromper ou manipuler.' },
    analyse: { consigne: 'Pourquoi peut-on dire que ce message est une manipulation ?', mots: [['logo'], ['faux', 'copié'], ['croire', 'tromper']], corrige: 'Ce message utilise le logo copié du collège pour faire croire qu\'il est officiel. Son auteur trompe volontairement les élèves.' },
    principe: { consigne: 'Identifie et définis la liberté dont il est question dans le document 2.', mots: [['liberté d\'expression'], ['opinion', 'pensées'], ['limite', 'abus', 'loi']], corrige: 'Il s\'agit de la liberté d\'expression : le droit de dire et d\'écrire ce que l\'on pense. Elle a des limites fixées par la loi, car on doit répondre de ses abus.' },
    explication: { consigne: 'Explique pourquoi les réseaux sociaux rendent les élèves vulnérables aux fausses informations. Illustre par deux exemples tirés des documents.', mots: [['partag'], ['vite', 'rapid', 'heure'], ['vérifi'], ['source']], corrige: 'Sur les réseaux sociaux, une information se partage très vite et sans contrôle. Dans le document 1, le message est partagé plus de 300 fois en une heure. Beaucoup d\'élèves le croient sans vérifier la source, car il porte le logo du collège. Certains restent même chez eux. Le démenti du principal arrive après la diffusion du message.' },
    texte: { consigne: 'Écris un texte pour sensibiliser tes camarades aux dangers des fausses informations et leur donner des conseils.', lignes: 8, mots: [['vérifi'], ['source'], ['partag'], ['responsab', 'loi']], corrige: 'Avant de partager un message, prends le temps de réfléchir. D\'abord, une fausse information peut faire beaucoup de dégâts : au collège, certains élèves ont manqué les cours à cause d\'un faux message. Ensuite, il faut toujours vérifier la source : le site officiel du collège ou un adulte peut confirmer une information. Méfie-toi des captures d\'écran, car un logo se copie facilement. Enfin, la liberté d\'expression a des limites : celui qui diffuse une fausse information peut être tenu pour responsable devant la loi. Donc, si tu as un doute, ne partage pas.' }
  },
  {
    id: 'image-truquee',
    titre: 'Une vidéo truquée',
    documents: [
      { titre: 'Une vidéo très partagée', html: '<p>Une vidéo montre un ministre qui semble annoncer la suppression des vacances d\'été. Elle est vue des milliers de fois en une journée. Des journalistes spécialisés dans la vérification des faits montrent qu\'elle a été fabriquée avec un logiciel d\'intelligence artificielle : la voix et les mouvements des lèvres ont été imités. Le ministre n\'a jamais dit cela.</p>', source: SITUATION_INVENTEE },
      { titre: 'Le rôle des journalistes', html: '<p>Dans une démocratie, la presse est libre. Des journalistes et des médias vérifient les informations, citent leurs sources et corrigent leurs erreurs. Des rubriques de « fact-checking » (vérification des faits) analysent les rumeurs qui circulent sur internet.</p>', source: 'Texte de synthèse rédigé pour l\'entraînement.' }
    ],
    definition: { consigne: 'Qu\'est-ce qu\'un « deepfake » (ou hypertrucage) ?', mots: [['vidéo', 'image', 'son'], ['intelligence artificielle', 'logiciel'], ['faux', 'truqu', 'fabriqu']], corrige: 'Un hypertrucage est une vidéo, une image ou un son fabriqué avec l\'intelligence artificielle pour faire croire qu\'une personne a dit ou fait quelque chose de faux.' },
    analyse: { consigne: 'Pourquoi cette vidéo est-elle dangereuse pour la démocratie ?', mots: [['tromper', 'croire'], ['citoyens'], ['confiance']], corrige: 'Elle trompe les citoyens en faisant croire qu\'un responsable politique a pris une décision qu\'il n\'a jamais prise. Elle abîme la confiance dans l\'information et dans les institutions.' },
    principe: { consigne: 'Identifie et définis la liberté qui permet aux journalistes de faire leur travail.', mots: [['liberté de la presse'], ['informer', 'publier'], ['censure', 'libre']], corrige: 'C\'est la liberté de la presse : les journalistes peuvent enquêter et publier des informations sans censure, dans le respect de la loi.' },
    explication: { consigne: 'Explique comment on peut se protéger des images truquées. Illustre par deux exemples.', mots: [['vérifi'], ['journalistes', 'médias', 'fact-checking'], ['source'], ['plusieurs']], corrige: 'Pour se protéger, il faut d\'abord se demander qui a publié l\'image ou la vidéo. On peut ensuite vérifier si des médias fiables en parlent aussi. Dans le document 1, des journalistes spécialisés ont montré que la vidéo était fabriquée. Les rubriques de vérification des faits, présentées dans le document 2, analysent les rumeurs. Enfin, il faut se méfier des contenus qui provoquent une émotion très forte.' },
    texte: { consigne: 'Écris un texte pour convaincre tes camarades de garder leur esprit critique face aux vidéos qui circulent en ligne.', lignes: 8, mots: [['esprit critique', 'critique'], ['vérifi'], ['source'], ['partag']], corrige: 'Aujourd\'hui, une vidéo peut sembler vraie et pourtant être totalement fausse. D\'abord, l\'intelligence artificielle permet d\'imiter la voix et le visage de n\'importe qui. Ensuite, ces vidéos sont faites pour nous faire réagir vite, avec de la colère ou de la peur. Garde donc ton esprit critique : demande-toi qui a publié la vidéo et cherche si des médias sérieux en parlent. Les journalistes qui vérifient les faits peuvent t\'aider. Enfin, ne partage jamais une vidéo dont tu n\'es pas sûr, car tu participerais à la tromperie.' }
  }
]);
