// Situations pratiques · Les principes et les valeurs de la République
import { fabriquerSituations, SITUATION_INVENTEE } from './fabrique-situation.js';

export default fabriquerSituations([
  {
    id: 'laicite',
    titre: 'La laïcité au collège',
    documents: [
      { titre: 'Une discussion en classe', html: '<p>Pendant un débat en classe, un élève demande pourquoi on ne peut pas porter de signe religieux très visible au collège, alors qu\'on peut le faire dans la rue. Une autre élève répond que la laïcité interdit les religions. Le professeur explique que ce n\'est pas exact et propose de lire les textes.</p>', source: SITUATION_INVENTEE },
      { titre: 'Deux textes de loi', html: '<p>« La République assure la liberté de conscience. Elle garantit le libre exercice des cultes […]. La République <u>ne reconnaît, ne salarie ni ne subventionne aucun culte</u>. »</p><p class="source">Loi de séparation des Églises et de l\'État, articles 1 et 2, 9 décembre 1905.</p><p>« Dans les écoles, les collèges et les lycées publics, le port de signes ou tenues par lesquels les élèves manifestent ostensiblement une appartenance religieuse est interdit. »</p>', source: 'Loi du 15 mars 2004 (Code de l\'éducation, article L. 141-5-1).' }
    ],
    definition: { consigne: 'Qu\'est-ce que la laïcité ?', mots: [['séparation', 'séparé'], ['religion', 'églises', 'culte'], ['neutre', 'liberté de conscience', 'croire']], corrige: 'La laïcité est le principe de séparation entre l\'État et les religions. L\'État est neutre et garantit à chacun la liberté de croire ou de ne pas croire.' },
    analyse: { consigne: 'L\'élève qui dit que « la laïcité interdit les religions » a-t-elle raison ? Justifie.', mots: [['non', 'tort'], ['liberté de conscience', 'libre exercice'], ['1905']], corrige: 'Non, elle a tort : la loi de 1905 garantit la liberté de conscience et le libre exercice des cultes. La laïcité protège toutes les croyances, sans en favoriser aucune.' },
    principe: { consigne: 'Identifie et définis le principe qui explique la règle de 2004 à l\'école publique.', mots: [['laïcité', 'laïque'], ['neutr'], ['école']], corrige: 'C\'est la laïcité de l\'école publique : l\'école est un lieu neutre, où les élèves ne doivent pas manifester ostensiblement leur religion, pour que chacun soit accueilli de la même façon.' },
    explication: { consigne: 'Explique pourquoi la laïcité protège tous les élèves. Illustre par deux exemples tirés des documents.', mots: [['liberté de conscience'], ['neutre', 'neutralité'], ['égalité', 'égaux'], ['croyances', 'religion']], corrige: 'La laïcité protège d\'abord la liberté de conscience : chacun peut croire ou ne pas croire, comme le garantit la loi de 1905. L\'État ne favorise aucune religion, car il ne reconnaît ni ne subventionne aucun culte. À l\'école publique, la loi de 2004 interdit les signes religieux ostensibles. Ainsi, aucun élève ne subit de pression à cause de sa religion ou de son absence de religion. Tous les élèves sont accueillis de manière égale.' },
    texte: { consigne: 'Écris un texte pour expliquer à tes camarades ce qu\'est vraiment la laïcité et pourquoi elle est importante au collège.', lignes: 8, mots: [['laïcité'], ['liberté'], ['égalité', 'égaux'], ['respect']], corrige: 'Beaucoup de personnes pensent que la laïcité est contre les religions, mais c\'est faux. D\'abord, la laïcité garantit la liberté de conscience : chacun peut croire ou ne pas croire, et pratiquer sa religion dans le respect de la loi. Ensuite, l\'État et l\'école publique restent neutres, ce qui permet d\'accueillir tous les élèves de la même manière. Au collège, on ne porte donc pas de signe religieux ostensible, pour que personne ne subisse de pression. Enfin, la laïcité nous apprend le respect des autres. Elle est une protection pour nous tous.' }
  },
  {
    id: 'egalite',
    titre: 'L\'égalité entre les filles et les garçons',
    documents: [
      { titre: 'Une équipe réservée aux garçons ?', html: '<p>Dans un club sportif, une jeune fille de 14 ans veut rejoindre l\'équipe de football de son âge, car il n\'existe pas d\'équipe féminine. L\'entraîneur refuse : « Le foot, ce n\'est pas pour les filles. » Ses parents rappellent que ce refus est une discrimination et préviennent le président du club, qui l\'accepte finalement dans l\'équipe.</p>', source: SITUATION_INVENTEE },
      { titre: 'L\'égalité dans la Constitution', html: '<p>« <u>La loi garantit à la femme, dans tous les domaines, des droits égaux à ceux de l\'homme.</u> »</p><p class="source">Préambule de la Constitution du 27 octobre 1946 (repris par la Constitution de 1958).</p><p>« La loi favorise l\'égal accès des femmes et des hommes aux mandats électoraux et fonctions électives, ainsi qu\'aux responsabilités professionnelles et sociales. »</p>', source: 'Constitution de la Ve République, article 1er.' }
    ],
    definition: { consigne: 'Qu\'est-ce qu\'une discrimination ?', mots: [['traiter', 'traitement', 'inégal'], ['différemment', 'défavorable'], ['sexe', 'origine', 'critère']], corrige: 'Une discrimination est le fait de traiter une personne moins bien qu\'une autre à cause d\'un critère interdit par la loi, comme son sexe, son origine ou sa religion.' },
    analyse: { consigne: 'Pourquoi le refus de l\'entraîneur est-il une discrimination ?', mots: [['fille', 'sexe'], ['refus', 'refuse'], ['seulement', 'parce que']], corrige: 'L\'entraîneur refuse la jeune fille seulement parce qu\'elle est une fille. Il la traite moins bien qu\'un garçon à cause de son sexe.' },
    principe: { consigne: 'Identifie et définis la valeur de la République remise en cause.', mots: [['égalité'], ['droits'], ['loi', 'même']], corrige: 'C\'est l\'égalité : tous les citoyens, femmes et hommes, ont les mêmes droits et doivent être traités de la même façon par la loi.' },
    explication: { consigne: 'Montre que la loi protège l\'égalité entre les femmes et les hommes. Illustre par deux exemples tirés des documents.', mots: [['égaux', 'égalité'], ['1946'], ['constitution'], ['discrimination']], corrige: 'La loi affirme l\'égalité entre les femmes et les hommes dans tous les domaines. Le préambule de 1946 garantit à la femme des droits égaux à ceux de l\'homme. La Constitution de 1958 favorise aussi l\'égal accès aux mandats électoraux et aux responsabilités. Dans le document 1, les parents rappellent que le refus de l\'entraîneur est une discrimination. Grâce à cette règle, la jeune fille peut finalement jouer dans l\'équipe.' },
    texte: { consigne: 'Écris un texte pour convaincre tes camarades de lutter contre les préjugés sur les filles et les garçons.', lignes: 8, mots: [['égalité'], ['préjugé', 'stéréotype', 'cliché'], ['discrimination'], ['respect']], corrige: 'Les filles et les garçons ont les mêmes droits, et pourtant les préjugés sont encore nombreux. D\'abord, des phrases comme « le foot, ce n\'est pas pour les filles » enferment les gens dans des rôles qu\'ils n\'ont pas choisis. Ensuite, ces préjugés peuvent conduire à des discriminations, qui sont punies par la loi. L\'égalité est une valeur de la République, inscrite dans la Constitution. Alors, encourage chacun à choisir son sport, ses études ou son métier librement. Enfin, si tu es témoin d\'une discrimination, parles-en à un adulte. Le respect de l\'égalité commence entre nous.' }
  }
]);
